# Main
url:                http://www.grison.me
title:              Alexandre Grison
author:             Alexandre Grison

# Jekyll Config
permalink:          /:year/:month/:title
markdown:           redcarpet
pygments:           true
exclude:            README.textile Rakefile
regeneration:       true
#lsi:                true

# Custom
related_limit:      5
excerpt_link:       "Read More&hellip;"

# Plugins
category_dir:       categories
index_pages:
  category:
    do_related:     false
    title_prefix:   'Category: '
  tag:
    do_related:     true
    title_prefix:   'Tag: '